import { Footer } from '@/components/layout/Footer'
import { Header } from '@/components/layout/Header'
import { Toaster } from '@/components/ui/toast/toaster'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ConvexClientProvider from './ConvexClientProvider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <Toaster />
          <div className="flex flex-col min-h-[100svh]">
            <Header />
            {children}
            <Footer />
          </div>
        </ConvexClientProvider>
      </body>
    </html>
  )
}
